// <auto-generated />
namespace BookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_tempsellinvoice_and_tempsellitem_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_tempsellinvoice_and_tempsellitem_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201907221417186_create_tempsellinvoice_and_tempsellitem_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
